{{- range $w := .Values.workloads }}
{{- if $w.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "distributed-app.workloadFullname" (dict "root" $ "workload" $w) }}
  labels:
{{ include "distributed-app.labels" (dict "root" $ "workload" $w) | indent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "distributed-app.workloadFullname" (dict "root" $ "workload" $w) }}
  minReplicas: {{ $w.autoscaling.minReplicas }}
  maxReplicas: {{ $w.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $w.autoscaling.targetCPUUtilizationPercentage }}
---
{{- end }}
{{- end }}
